name: iosApp
options:
  bundleIdPrefix: info.plateaukao
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    ENABLE_USER_SCRIPT_SANDBOXING: NO
targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - iosApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: info.plateaukao.einkbro.ios
        PRODUCT_NAME: EinkBro
        INFOPLIST_FILE: iosApp/Info.plist
        FRAMEWORK_SEARCH_PATHS: $(inherited) $(SRCROOT)/../composeApp/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)
        OTHER_LDFLAGS: $(inherited) -framework ComposeApp
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
    preBuildScripts:
      - name: Compile Kotlin Framework
        basedOnDependencyAnalysis: false
        script: |
          cd "$SRCROOT/.."
          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode
